# Generated by Django 4.2.7 on 2023-11-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='share_type',
            field=models.CharField(choices=[('EQUAL', 'Equal'), ('EXACT', 'Exact'), ('PERCENT', 'Percent'), ('SHARE', 'Share')], default='EQUAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='expenseparticipant',
            name='share_type',
            field=models.CharField(choices=[('EQUAL', 'Equal'), ('EXACT', 'Exact'), ('PERCENT', 'Percent'), ('SHARE', 'Share')], default='EQUAL', max_length=50),
        ),
    ]
